Feat/errorhandling in friends search into Develop
COS301-SE-2024/GameOnConnect pull request #205
Opened 2024-06-27 21:05 UTC by pieryvdl

I removed all the print statements and replaced them with toast messages. For a preview of how it would look when an eroor pops up, you can look at the Add to Wishlist and Add to Currently Playing buttons on the game_details page. It looks quite nice! The toasts also stack upon each other and automatically dissapear after a while, the only downside is we have less styling capability. But it could be looked into. Have a look and let me know. 😊

2024-06-28 05:52 UTC, MonikaTheiss commented on lib/pages/friends_page.dart
The code here looks good and you added a lot of error handling code, which is good. I'm just wondering, since these messages will now be seen by the user, if we shouldn't give them more detailed/easier to understand errors? I feel like if we say " error getting friends" or something like that , that's not really language the user would easily understand. I don't know if its just me though

2024-06-28 06:08 UTC, MonikaTheiss requested changes
The toasts look very cool !  I tried out the add to wishlist and add to currently playing ones, I like how they popup and disappear to the side . They are a bit difficult to see however, especially since the user is looking at the bottom of the screen to click on the buttons, they might miss it , because the background is white like the rest of the page and the text is green like the rest of the page , so its difficult to notice the toast before it dissappears

2024-06-28 07:16 UTC, pieryvdl commented on lib/pages/friends_page.dart
We can definitely look into doing this. I can change the text a bit to be more descriptive? 😄

2024-06-28 07:18 UTC, pieryvdl commented
I agree, I wanted to style it a bit more. Will look into how we could possibly do that. I will close the pull request for now and then work on it a bit more.

2024-07-01 17:23 UTC, pieryvdl commented
I added a border and modified the toast to use a Custom Toast instead, so we can easily style the toasts to how we want them.

2024-07-01 18:25 UTC, pieryvdl commented
I found more code that needs to be error tested.

2024-07-01 19:36 UTC, pieryvdl commented
Added the code to not show and rather show to check internet connection..

2024-07-02 09:16 UTC, MonikaTheiss approved these changes
Code looks good, could you maybe let the toast message stay a bit longer or make the message shorter? I struggled to read the whole message before it disappeared. In dark mode the border of the toast is a bit difficult to see, but at least the green is visible. I think the rest is fine for now. Otherwise you would be stuck on this forever. Thank you for making the toasts more readable !

2024-07-03 09:36 UTC, pieryvdl commented
@u22520016 @MonikaTheiss I made the duration even longer. Just need your final approval then we can merge this in. I will move on to the work assigned this week.

2024-07-04 11:45 UTC, MonikaTheiss approved these changes

2024-07-05 10:49 UTC, u22520016 approved these changes
Looks good.

2024-07-05 13:41 UTC, merged