Fix/themebugs into Devlop
COS301-SE-2024/GameOnConnect pull request #473
Opened 2024-08-16 11:10 UTC by pieryvdl

Hey guys here is the theme fixes. 

You'll notice I changed some of the code regarding how themes work.
Another major change is going from yellow to orange as a color. 

It took me quite a while longer than I expected it would. But I wanted to get the contrasts right for all the colors. 
Please let me know what you think!

2024-08-19 06:39 UTC, MonikaTheiss commented
waiting for a new api key and then I will be able to look at this

2024-08-19 16:50 UTC, MonikaTheiss requested changes
Looks very cool ! I did speak to you about the blue light mode color and sent a screenshot

2024-08-19 18:18 UTC, MonikaTheiss approved these changes
Looks good thank you! I really like the new colors 😄

2024-08-20 06:51 UTC, LeratoKgomo approved these changes

2024-08-20 06:51 UTC, merged